### ISSUE TITLE
Comment for Reply messages is not displayed

### ISSUE THREAD

**Issue by MrCoder** [mermaid-js/zenuml-core#101]
```
A.method1 {
    // comment
    @return B->C: Self Async
}
```
Correct behaviour: tag - v2.0.38.
<img width="822" alt="image" src="https://github.com/mermaid-js/zenuml-core/assets/169417/a6abeeb1-8258-4e59-8f19-d11e634f1b9f">

Wrong behaviour: tag - v3.15.4
<img width="698" alt="image" src="https://github.com/mermaid-js/zenuml-core/assets/169417/b7717256-c551-403e-91d2-db47c72eeefc">

**Comment by dyon21** [comment]
Fixed in #103
