### ISSUE TITLE
Styling messages

### ISSUE THREAD

**Issue by MrCoder** [mermaid-js/zenuml-core#16]
```
// [red, bold]
A.method()
```
Should render the message in red and message text in bold. It must only style the current message and should not have impact on its children or siblings.
<img width="609" alt="Screenshot 2023-07-01 at 7 45 18 pm" src="https://github.com/mermaid-js/zenuml-core/assets/169417/8e0cece6-114f-4e7e-9bfd-a0350188a0d2"> 

We can do a lot more with this syntax.
tailwind css and s

hortcuts can be used:

text-red-900
text-red
red
font-bold
bold

**Comment by MrCoder** [comment]
## 1. Introduction

Styling annotations are defined as metadata that specify the visual representation of a given message or fragment. This document defines the rules for parsing these annotations and rendering the associated diagram.

## 2. Language Specification and Parsing

This section outlines the syntax and behaviour rules for the parser:

1. The annotation MUST be placed at the beginning of the last line of a comment block.
2. The annotation MUST be encapsulated within square brackets `[]`.
3. Whitespace characters, specifically spaces (represented as `\s`) and tabs (represented as `\t`), MUST be disregarded between the marker `//` and `[]`.
4. Multiple styles can be defined within the annotation by separating them with a comma `,`.
5. The valid characters for the style keywords are alphanumeric characters (0-9, A-Z, a-z) and the hyphen `-`.
6. In the event of encountering unrecognised keywords during parsing, the process MUST continue without interruption. However, reporting such occurrences as errors is RECOMMENDED.

### 2.1 Examples

Below are examples of valid annotations:

1. // [red] other content of the comment
2. //[green,bold]

## 3. Rendering

This section describes the rules for rendering the styled content:

1. In the event of conflicting styles, a single style MUST be applied. The choice of which style to apply is not specified in this document.
2. Implementations are permitted to define their own list of supported keywords. However, they MUST ensure that the presence of unrecognised keywords does not disrupt the rendering process.
3. Renderers SHOULD, but are not required to, include any unrecognised keywords in the class list.
4. The style MUST be applied to the message. Whenever applicable it CAN be applied to the arrow and/or the message bar. Note that when the style applies to the message bar, it MUST also apply to the arrow.
5. When applied to fragments, the style MUST be applied to the keywords (e.g. `if`, `loop`, 'try` etc.). Whenever applicable, it SHOULD also be applied to the frame of the fragments.
6. The style MUST also apply to the comment if it contains extra content. This includes the lines above the last line. It MUST NOT be treated as a newline when combining the comments.

**Comment by dyon21** [comment]
This feature has been implemented in #30 

Note: dividers can also be styled by same syntax (` === [red] a divider ===`)
