### ISSUE TITLE
Zoom in/out button must not move along with other parts of the diagram when they are clicked.

### ISSUE THREAD

**Issue by MrCoder** [mermaid-js/zenuml-core#17]
Currently when you click Zoom in or out button, the button will move away.

Moved to here from https://github.com/ZenUml/core/issues/435

**Comment by R0uter** [comment]
Move the zoom control to the top left as our diagram anchors there so that the control will not move away after zoom changes.

**Comment by R0uter** [comment]
PR created at https://github.com/mermaid-js/zenuml-core/pull/19
