### ISSUE TITLE
`peerDependency` warning/error when installing `@zenuml/core` due to `vue-property-decorator`

### ISSUE THREAD

**Issue by aloisklink** [mermaid-js/zenuml-core#225]
It looks like the `dependency` `vue-property-decorator`:

https://github.com/mermaid-js/zenuml-core/blob/904d6c374503c49c9eae4b8694f5e02d0f6cae39/package.json#L65

Has a [`peerDependencies` on `"vue-class-component": "*"`](https://github.com/kaorun343/vue-property-decorator/blob/e04872349bab357e6d08b01442f83abc9976eb50/package.json#L43),

which then has a `peerDependencies` on `"vue": "^2.0.0"`:

https://github.com/vuejs/vue-class-component/blob/b866fde8ba1ef8cf29fa44f26d19b3167ecae1dd/package.json#L46-L48

However, since `zenuml-core` has a `dependency` on `"vue": "^3.2.4"`:

https://github.com/mermaid-js/zenuml-core/blob/904d6c374503c49c9eae4b8694f5e02d0f6cae39/package.json#L64

This causes some package managers to throw a warning/error when installing `@zenuml/core`, e.g.

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

my-app
└─┬ vue-class-component 7.2.6
  └── ✕ unmet peer vue@^2.0.0: found 3.5.13
```

### Potential fix

It looks you can might be able to replace `vue-property-decorator` with [`vue-facing-decorator`](https://www.npmjs.com/package/vue-facing-decorator), which does official support Vue 3, see <https://github.com/kaorun343/vue-property-decorator/blob/e04872349bab357e6d08b01442f83abc9976eb50/README.md?plain=1#L2-L4>

> # [DEPRECATED] Vue Property Decorator
> ## ⚠️ Notice
> This library is no longer actively maintained. If you still want to use classes, check out the community-maintained project [`vue-facing-decorator`](https://facing-dev.github.io/vue-facing-decorator/#/).

**Comment by ReDemoNBR** [comment]
I have the same issue, but I use `npm` instead `pnpm`
