### ISSUE TITLE
Style should effect only on Zenuml component.

### ISSUE THREAD

**Issue by tfsojon** [mermaid-js/zenuml-core#29]
It's changes the default style of a webpage.

![image](https://github.com/mermaid-js/zenuml-core/assets/87603786/944d2f6d-3117-4f65-acc1-962b2adafe94)

**Comment by MrCoder** [comment]
Is it the same issue as https://github.com/mermaid-js/zenuml-core/issues/18?

**Comment by tfsojon** [comment]
Opps. 
Yes I think the problem is same.
So i am closing this issue.
if the style render with the wrap of a `.zenuml` it will solve the problem I think.

thanks
