### ISSUE TITLE
RFC: Styling messages and comments separately

### ISSUE THREAD

**Issue by MrCoder** [mermaid-js/zenuml-core#60]
In our current implementation, we use the following syntax to control the style for both comments and messages. However, it would be good (?) that we could control them separately.

```
// [red] comments
A.method
```
The proposed solution:

1. `<red>` controls comment only;
2. `(red)` controls message only;
3. `[red]` controls both comment and message.

**Comment by dyon21** [comment]
All style brackets should appear before the first non-empty character

**Comment by MrCoder** [comment]
> All style brackets should appear before the first non-empty character

Yes. And they should appear only at the last line of comment. Only one type of styling annotation should appear.

Wrong:
```
// [red] comment
// another line of comment
```
Wrong:
```
// <red>(blue) comment
```

**Comment by dyon21** [comment]
Why do we not allow multiple annotations? Users may want to set different styles to both comments and messages respectively.

**Comment by dyon21** [comment]
#108
