### ISSUE TITLE
Alt Fragment Overflows the Diagram Frame

### ISSUE THREAD

**Issue by MrCoder** [mermaid-js/zenuml-core#90]
Code to reproduce:
```
ALPN as _ALongParticipantName_MustUseAs_
A

A -> A: message with 'From' defined, and pre-declared

A ->B.check{
  if (condition){
    C.method
  }
}
```
Note that the code is very carefully crafted to reproduce this issue.
![image](https://github.com/mermaid-js/zenuml-core/assets/169417/c2ada3f1-3a62-46fd-a9fc-451e8910693d)

**Comment by dontry** [comment]
Root cause analysis: the cached width of the participant ALPN is incorrect.

**Comment by dontry** [comment]
When calculating the width of the participant, it's using the name of the participant i.e. "ALPN", not the actual label "_ALongParticipantName_MustUseAs_"
